sca: make pc: provides/vendored use full package version
.pc file version can be an aribitrary string value, without any
relation to soname, nor semver.

This yields the very opaque errors

    provides = pc:gdal=3.8.5dev
    datahash = c4638ec49b51aac1fc8f1d948b06a5b6c7a9f41dca2f980629b1f12f8e8be711
    ERROR: ./packages/x86_64/gdal-3.8-dev-3.8.5-r0.apk: package file format error

Which pointlessly waste engineering time.

Node we do not generate depends on pc: provides, as currently
`wolfictl text` transitive dependencies checks are unable to resolve
these.

Fixes: https://github.com/chainguard-dev/melange/issues/1172

Note there is sense that this may have been a missfeature in abuilds
too.